import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { Mapa } from '../components/Mapa'
import { Menu } from '../components/Menu'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Menu />

        <h1 className={styles.title} style={{ marginTop: "1rem" }}>
          Rezervátor skautských kluboven
        </h1>
        {/*<Mapa />*/}

        
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/logo.svg" alt="Vercel Logo" width={100} height={50} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
