import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { Mapa } from '../components/Mapa'
import { Menu } from '../components/Menu'
import styles from '../styles/Home.module.css'
import styled from "styled-components";
import Link from 'next/link'

const Odkaz = styled.span`
    color: #6B96CA;
`;

const Obsah = styled.main`
    min-height: 100vh;
    padding: 4rem 0;
    flex: 1;
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
`;

const Container = styled.div`
  padding: 0 2rem;
`;

const Nadpis = styled.h1`
    text-align: center;
    margin: 0;
    line-height: 1.15;
    font-size: 4rem;
`;

const Podnadpis = styled.h3`
    margin-top: 5rem;
    background-color: #D19C95;
    padding: 1rem;
    border-radius: 1rem;
    border: solid 1px #A38456;
`;

const Tip = styled.h3`
    font-size: 80%;
    background-color: #ECA038;
    padding: .7rem;
    border: solid 1px #A38456;
    border-radius:1rem
`;

const Home: NextPage = () => {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Obsah>

        <Nadpis>Rezervátor skautských kluboven</Nadpis>
        <Podnadpis>Pro přidání klubovny se přihlaš, pro prohlížení kluboven přejdi na záložku <Odkaz><Link href="./prohlizec">Prohlížeč kluboven</Link></Odkaz>.</Podnadpis>
        <Tip>Tip: Pokud si chceš uložit klubovnu do oblíbených porovnávat je a hodnotit je, přihlaš se na svůj účet.</Tip>
        {/*<Mapa />*/}

        
        <Menu />
      </Obsah>

      {/*<footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/logo.svg" alt="Vercel Logo" width={100} height={50} />
          </span>
        </a>
  </footer>*/}
    </Container>
  )
}

export default Home
